### ISSUE TITLE
~ in temporary path makes it unreadable for curl

### ISSUE THREAD

**Issue by jtpedersen** [xenodium/shell-maker#1]
In https://github.com/xenodium/shell-maker/blob/ead7b8a126ad1e631d9a9f605644192799abea0f/shell-maker.el#L1247

if `temporary-file-directory` is `~/emacs-tmp` then curl will fail with: 

```
Warning: Couldn't read data from file "~/emacs-tmp/shell-maker/curl-data", 
Warning: this makes an empty POST.
```

Suggested, (and not so tested), fix:
``` lisp
(defun shell-maker--temp-file (&rest components)
  "Create an absolute temp file path for COMPONENTS."
  (let* ((components (cons "shell-maker" components))
         (relative-path (apply #'file-name-concat components))
         (temp-file (expand-file-name relative-path temporary-file-directory)))
    (make-directory (file-name-directory temp-file) t)
    temp-file))
```

I ended up fixing *my* concrete issue by using `expand-file-name` on my custom `temporary-file-directory`

**Comment by xenodium** [comment]
Ah thanks for this! Will patch soon.

**Comment by xenodium** [comment]
Thanks for the patch. Works for me. Applied in https://github.com/xenodium/shell-maker/commit/e041514f3be05b4b24eb0edab12313c1784f45eb

Gonna close issue. Please reopen if if you still run issues.
